"""Add time_zone column

Revision ID: 004e7c2b2f46
Revises: e77cbc0e4587
Create Date: 2025-04-26 16:20:09.647477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004e7c2b2f46'
down_revision = 'e77cbc0e4587'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('time_zone', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'time_zone')
    # ### end Alembic commands ###
