"""Add frequency to subscriber

Revision ID: 186cb689f77e
Revises: 004e7c2b2f46
Create Date: 2025-04-26 16:38:30.347122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186cb689f77e'
down_revision = '004e7c2b2f46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
