"""Create subscribers table

Revision ID: 3884d31765c4
Revises: 90b02e51cf19
Create Date: 2025-04-24 09:48:35.570706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3884d31765c4'
down_revision = '90b02e51cf19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
