"""Replace Quote with Subscriber

Revision ID: 90b02e51cf19
Revises: 7d00a5ba126b
Create Date: 2025-04-24 09:36:06.260434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90b02e51cf19'
down_revision = '7d00a5ba126b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
