"""A small fix to time zone

Revision ID: 9ec43f5f9093
Revises: 186cb689f77e
Create Date: 2025-04-26 16:45:21.010134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec43f5f9093'
down_revision = '186cb689f77e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('frequency', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'frequency')
    # ### end Alembic commands ###
