"""updates

Revision ID: e77cbc0e4587
Revises: b7b523f2bde4
Create Date: 2025-04-25 16:40:03.828681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77cbc0e4587'
down_revision = 'b7b523f2bde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('categories', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'categories')
    # ### end Alembic commands ###
