from flask import Flask, jsonify, request
from flask_cors import CORS
import random

app = Flask(__name__)

CORS(app, origins="*")

subscribers = []

quotes = {
    "philosophy": [
        {"quote": "The unexamined life is not worth living.", "author": "Socrates"},
        {"quote": "I think, therefore I am.", "author": "René Descartes"},
        {"quote": "He who thinks great thoughts, often makes great errors.", "author": "Martin Heidegger"},
        {"quote": "Happiness is the highest good.", "author": "Aristotle"},
        {"quote": "Man is condemned to be free.", "author": "Jean-Paul Sartre"},
        {"quote": "To be is to be perceived.", "author": "George Berkeley"},
        {"quote": "Liberty consists in doing what one desires.", "author": "John Stuart Mill"},
        {"quote": "God is dead. God remains dead. And we have killed him.", "author": "Friedrich Nietzsche"},
        {"quote": "The only thing I know is that I know nothing.", "author": "Socrates"},
        {"quote": "Life must be understood backward. But it must be lived forward.", "author": "Søren Kierkegaard"},
        {"quote": "Freedom is the recognition of necessity.", "author": "Georg Wilhelm Friedrich Hegel"},
        {"quote": "Even while they teach, men learn.", "author": "Seneca"},
        {"quote": "The greatest happiness of the greatest number is the foundation of morals and legislation.", "author": "Jeremy Bentham"},
        {"quote": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "author": "Aristotle"},
        {"quote": "That which does not kill us makes us stronger.", "author": "Friedrich Nietzsche"},
        {"quote": "Hell is other people.", "author": "Jean-Paul Sartre"},
        {"quote": "No man's knowledge here can go beyond his experience.", "author": "John Locke"},
        {"quote": "Happiness lies in virtuous activity, and perfect happiness lies in the best activity, which is contemplative.", "author": "Aristotle"},
        {"quote": "Time is a moving image of eternity.", "author": "Plato"},
    {"quote": "Knowing others is intelligence; knowing yourself is true wisdom. Mastering others is strength; mastering yourself is true power.", "author": "Lao Tzu"},
    {"quote": "The life of man is solitary, poor, nasty, brutish, and short.", "author": "Thomas Hobbes"},
    {"quote": "An unexamined life is not worth living.", "author": "Socrates"},
    {"quote": "I cannot teach anybody anything. I can only make them think.", "author": "Socrates"},
    {"quote": "There is only one good, knowledge, and one evil, ignorance.", "author": "Socrates"},
    {"quote": "Philosophy is a battle against the bewitchment of our intelligence by means of language.", "author": "Ludwig Wittgenstein"},
    {"quote": "The greatest enemy of knowledge is not ignorance, it is the illusion of knowledge.", "author": "Stephen Hawking"},
    {"quote": "We do not remember days, we remember moments.", "author": "Cesare Pavese"},
    {"quote": "It is not what happens to you, but how you react to it that matters.", "author": "Epictetus"},
    {"quote": "What is rational is actual, and what is actual is rational.", "author": "Georg Wilhelm Friedrich Hegel"},
    {"quote": "To live is to suffer, to survive is to find some meaning in the suffering.", "author": "Friedrich Nietzsche"},
    {"quote": "The mind is everything. What you think you become.", "author": "Buddha"},
    {"quote": "It is not length of life, but depth of life.", "author": "Ralph Waldo Emerson"},
    {"quote": "There are no facts, only interpretations.", "author": "Friedrich Nietzsche"},
    {"quote": "Man is the measure of all things.", "author": "Protagoras"},
    {"quote": "Happiness depends upon ourselves.", "author": "Aristotle"},
    {"quote": "All that we are is the result of what we have thought.", "author": "Buddha"},
    {"quote": "A good conscience is a continual Christmas.", "author": "Benjamin Franklin"},
    {"quote": "It is not the length of life, but depth of life.", "author": "Ralph Waldo Emerson"},
    {"quote": "Life without music would be a mistake.", "author": "Friedrich Nietzsche"},
    {"quote": "The only thing we have to fear is fear itself.", "author": "Franklin D. Roosevelt"},
    {"quote": "A fool thinks himself to be wise, but a wise man knows himself to be a fool.", "author": "William Shakespeare"},
    {"quote": "The more I read, the more I acquire, the more certain I am that I know nothing.", "author": "Voltaire"},
    {"quote": "To be is to do.", "author": "Immanuel Kant"},
    {"quote": "The greatest wealth is to live content with little.", "author": "Plato"},
    {"quote": "The highest form of ignorance is when you reject something you don't know anything about.", "author": "Wayne Dyer"},
    {"quote": "Life is not measured by the number of breaths we take, but by the moments that take our breath away.", "author": "George Carlin"},
    {"quote": "You have to be odd to be number one.", "author": "Dr. Seuss"},
    {"quote": "The true sign of intelligence is not knowledge but imagination.", "author": "Albert Einstein"},
    {"quote": "The first step toward philosophy is skepticism.", "author": "René Descartes"},
    {"quote": "I am not what happened to me, I am what I choose to become.", "author": "Carl Jung"},
    {"quote": "The good for man is an activity of the soul in accordance with virtue.", "author": "Aristotle"},
    {"quote": "Not to be a philosopher is to be a slave to things.", "author": "Søren Kierkegaard"},
    {"quote": "Those who are not busy being born are busy dying.", "author": "Bob Dylan"},
    {"quote": "The unexamined life is not worth living, but the unexamined death is also not worth dying.", "author": "Socrates"},
    {"quote": "To know, is to know that you know nothing. That is the meaning of true knowledge.", "author": "Socrates"},
    {"quote": "We live in capitalism. Its power seems inescapable. So did the divine right of kings.", "author": "Sylvia Plath"},
    {"quote": "There is only one way to avoid criticism: do nothing, say nothing, and be nothing.", "author": "Aristotle"},
    {"quote": "Man is the only creature who refuses to be what he is.", "author": "Albert Camus"},
    {"quote": "The greatest obstacle to discovery is not ignorance – it is the illusion of knowledge.", "author": "Daniel J. Boorstin"},
    {"quote": "The more one suffers, the more one is able to appreciate the beauty of life.", "author": "Friedrich Nietzsche"},
    {"quote": "It is not how old you are, but how you are old.", "author": "Jules Renard"},
    {"quote": "What is rational is real, and what is real is rational.", "author": "Georg Wilhelm Friedrich Hegel"},
    {"quote": "A man is but the product of his thoughts. What he thinks, he becomes.", "author": "Mahatma Gandhi"},
    {"quote": "An eye for an eye only ends up making the whole world blind.", "author": "Mahatma Gandhi"},
    {"quote": "The mind that opens to a new idea never returns to its original size.", "author": "Albert Einstein"},
    {"quote": "I would rather be a little nobody, than to be an evil somebody.", "author": "Abraham Lincoln"},
    {"quote": "The most important thing is to try to inspire people so that they can be great in whatever they want to do.", "author": "Kobe Bryant"},
    {"quote": "What can be asserted without evidence can also be dismissed without evidence.", "author": "Christopher Hitchens"},
    {"quote": "Knowing others is intelligence; knowing yourself is true wisdom.", "author": "Lao Tzu"},
    {"quote": "To be, or not to be, that is the question.", "author": "William Shakespeare"},
    {"quote": "We are what we think. All that we are arises with our thoughts. With our thoughts, we make the world.", "author": "Buddha"},
    {"quote": "The only way to deal with this life meaningfully is to find one's passion and pursue it.", "author": "Søren Kierkegaard"},
    {"quote": "The essence of being human is the ability to make choices.", "author": "Jean-Paul Sartre"},
    {"quote": "Man is free at the moment he wishes to be.", "author": "Voltaire"},
    {"quote": "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.", "author": "Ralph Waldo Emerson"},
    {"quote": "I can resist anything except temptation.", "author": "Oscar Wilde"},
    {"quote": "He who has a why to live can bear almost any how.", "author": "Friedrich Nietzsche"},
    {"quote": "One cannot step twice in the same river, for fresh waters are ever flowing in upon you.", "author": "Heraclitus"},
    {"quote": "Life without love is like a tree without blossoms or fruit.", "author": "Khalil Gibran"},
    {"quote": "We are all in the gutter, but some of us are looking at the stars.", "author": "Oscar Wilde"},
    {"quote": "A person who never made a mistake never tried anything new.", "author": "Albert Einstein"},
    {"quote": "I never think of the future. It comes soon enough.", "author": "Albert Einstein"}

    ],
    "humor": [
        {"quote": "I'm not arguing, I'm just explaining why I'm right.", "author": "Unknown"},
        {"quote": "I'm on a whiskey diet. I've lost three days already.", "author": "Tommy Cooper"},
        {"quote": "Why don’t scientists trust atoms? Because they make up everything!", "author": "Unknown"},
        {"quote": "I can resist everything except temptation.", "author": "Oscar Wilde"},
        {"quote": "I used to think I was indecisive, but now I'm not so sure.", "author": "Unknown"},
        {"quote": "A day without laughter is a day wasted.", "author": "Charlie Chaplin"},
        {"quote": "Behind every great man is a woman rolling her eyes.", "author": "Jim Carrey"},
        {"quote": "If you think nobody cares if you're alive, try missing a couple of payments.", "author": "Earl Wilson"},
        {"quote": "I'm not superstitious, but I am a little stitious.", "author": "Michael Scott"},
        {"quote": "You can't have everything. Where would you put it?", "author": "Steven Wright"},
        {"quote": "If at first you don't succeed, then skydiving definitely isn't for you.", "author": "Steven Wright"},
        {"quote": "I intend to live forever. So far, so good.", "author": "Steven Wright"},
        {"quote": "The road to success is always under construction.", "author": "Lily Tomlin"},
        {"quote": "Age is of no importance unless you're a cheese.", "author": "Billie Burke"},
        {"quote": "People say nothing is impossible, but I do nothing every day.", "author": "A.A. Milne (Winnie the Pooh)"},
        {"quote": "Light travels faster than sound. This is why some people appear bright until you hear them speak.", "author": "Alan Dundes"},
        {"quote": "To steal ideas from one person is plagiarism; to steal from many is research.", "author": "Wilson Mizner"},
        {"quote": "I always wanted to be somebody, but now I realize I should have been more specific.", "author": "Lily Tomlin"},
        {"quote": "Insanity is hereditary; you get it from your children.", "author": "Sam Levenson"},
        {"quote": "A clear conscience is usually the sign of a bad memory.", "author": "Steven Wright"},
        {"quote": "My fake plants died because I did not pretend to water them.", "author": "Mitch Hedberg"},
        {"quote": "I used to sell furniture for a living. The trouble was, it was my own.", "author": "Les Dawson"},
        {"quote": "I refuse to join any club that would have me as a member.", "author": "Groucho Marx"},
        {"quote": "I told my wife the truth. I told her I was seeing a psychiatrist. Then she told me the truth: that she was seeing a psychiatrist, two plumbers, and a bartender.", "author": "Rodney Dangerfield"},
        {"quote": "I find television very educational. Every time someone turns it on, I go in the other room and read a book.", "author": "Groucho Marx"},
        {"quote": "Get your facts first, then you can distort them as you please.", "author": "Mark Twain"},
        {"quote": "The best way to teach your kids about taxes is by eating 30% of their ice cream.", "author": "Bill Murray"},
        {"quote": "I haven't spoken to my wife in years. I didn’t want to interrupt her.", "author": "Rodney Dangerfield"},
        {"quote": "The surest sign that intelligent life exists elsewhere in the universe is that it has never tried to contact us.", "author": "Bill Watterson (Calvin & Hobbes)"},
        {"quote": "Do not take life too seriously. You will never get out of it alive.", "author": "Elbert Hubbard"},
        {"quote": "I asked God for a bike, but I know God doesn’t work that way. So I stole a bike and asked for forgiveness.", "author": "Emo Philips"},
        {"quote": "When life gives you lemons, squirt someone in the eye.", "author": "Cathy Guisewite"},
        {"quote": "I cook with wine. Sometimes I even add it to the food.", "author": "W.C. Fields"},
    {"quote": "I poured spot remover on my dog. Now he's gone.", "author": "Steven Wright"},
    {"quote": "Before you judge a man, walk a mile in his shoes. After that, who cares? He’s a mile away and you’ve got his shoes.", "author": "Billy Connolly"},
    {"quote": "I told my computer I needed a break, and now it won’t stop sending me beach ads.", "author": "Unknown"},
    {"quote": "There is no sunrise so beautiful that it is worth waking me up to see it.", "author": "Mindy Kaling"},
    {"quote": "I am not lazy. I am on energy-saving mode.", "author": "Unknown"},
    {"quote": "Life is short. Smile while you still have teeth.", "author": "Mallory Hopkins"},
    {"quote": "Why is it that our children can't read a Bible in school, but they can in prison?", "author": "Unknown"},
    {"quote": "I'm not lazy, I'm just very relaxed.", "author": "Garfield (Jim Davis)"},
    {"quote": "The only time to be positive you don’t have a hangover is when you’re dead.", "author": "Unknown"},
    {"quote": "I wish I were a little kid so I could take a nap and everyone would just be proud of me.", "author": "Unknown"},
    {"quote": "You know you’re getting old when the candles cost more than the cake.", "author": "Bob Hope"},
    {"quote": "My therapist says I have a preoccupation with vengeance. We’ll see about that.", "author": "Stewart Francis"},
    {"quote": "Clothes make the man. Naked people have little or no influence in society.", "author": "Mark Twain"},
    {"quote": "I've had bad luck with both my wives. The first one left me, and the second one didn’t.", "author": "Patrick Murray"},
    {"quote": "A computer once beat me at chess, but it was no match for me at kickboxing.", "author": "Emo Philips"},
    {"quote": "Common sense is like deodorant. The people who need it most never use it.", "author": "Unknown"},
    {"quote": "I want my children to have all the things I couldn't afford. Then I want to move in with them.", "author": "Phyllis Diller"},
    {"quote": "Never go to a doctor whose office plants have died.", "author": "Erma Bombeck"},
    {"quote": "I haven’t spoken to my wife in years. I didn’t want to interrupt her.", "author": "Rodney Dangerfield"},
    {"quote": "I dream of a better tomorrow, where chickens can cross the road and not be questioned about their motives.", "author": "Ralph Waldo Emerson (attributed humorously)"},
    {"quote": "I cook with wine, sometimes I even add it to the food.", "author": "W.C. Fields"},
    {"quote": "Some people graduate with honors, I am just honored to graduate.", "author": "Unknown"},
    {"quote": "My favorite machine at the gym is the vending machine.", "author": "Caroline Rhea"},
    {"quote": "The four most beautiful words in our common language: I told you so.", "author": "Gore Vidal"},
    {"quote": "The difference between stupidity and genius is that genius has its limits.", "author": "Albert Einstein (attributed)"},
    {"quote": "Don't worry about the world coming to an end today. It's already tomorrow in Australia.", "author": "Charles Schulz"},
    {"quote": "My bed is a magical place where I suddenly remember everything I forgot to do.", "author": "Unknown"},
    {"quote": "Laziness is nothing more than the habit of resting before you get tired.", "author": "Jules Renard"},
    {"quote": "I find television very educating. Every time somebody turns on the set, I go into the other room and read a book.", "author": "Groucho Marx"},
    {"quote": "I’m not great at the advice. Can I interest you in a sarcastic comment?", "author": "Chandler Bing (Friends)"},
    {"quote": "I always arrive late at the office, but I make up for it by leaving early.", "author": "Charles Lamb"},
    {"quote": "A balanced diet means a cupcake in each hand.", "author": "Unknown"},
    {"quote": "Procrastinate now, don't put it off.", "author": "Ellen DeGeneres"},
    {"quote": "If you can't dazzle them with brilliance, baffle them with nonsense.", "author": "W.C. Fields"},
    {"quote": "I am so clever that sometimes I don’t understand a single word of what I am saying.", "author": "Oscar Wilde"},
    {"quote": "I used to play sports. Then I realized you can buy trophies. Now I’m good at everything.", "author": "Demetri Martin"},
    {"quote": "I have not failed. I’ve just found 10,000 ways that won’t work.", "author": "Thomas Edison (often quoted humorously)"},
    {"quote": "When nothing is going right, go left.", "author": "Unknown"},
    {"quote": "You know you're getting old when the candles cost more than the cake.", "author": "Bob Hope"},
    {"quote": "Never put off until tomorrow what you can do the day after tomorrow just as well.", "author": "Mark Twain"},
    {"quote": "If you think nobody cares about you, try missing a couple of car payments.", "author": "Steven Wright"},
    {"quote": "I'm not lazy, I'm just on my energy-saving mode.", "author": "Unknown"},
    {"quote": "My wife and I were happy for twenty years. Then we met.", "author": "Rodney Dangerfield"},
    {"quote": "They say don't try this at home… so I'm coming over to your place!", "author": "Unknown"},
    {"quote": "Before you criticize someone, walk a mile in their shoes. That way you’ll be a mile away and you’ll have their shoes.", "author": "Jack Handey"},
    {"quote": "Why do they lock gas station bathrooms? Are they afraid someone will clean them?", "author": "George Carlin"},
    {"quote": "Money can’t buy happiness, but it can buy ice cream, and that’s kind of the same thing.", "author": "Unknown"},
    {"quote": "Knowledge is knowing a tomato is a fruit. Wisdom is not putting it in a fruit salad.", "author": "Miles Kington"},
    {"quote": "I hate when people use big words just to make themselves sound perspicacious.", "author": "Unknown"},
    {"quote": "The early bird might get the worm, but the second mouse gets the cheese.", "author": "Steven Wright"},
    {"quote": "I'm writing a book on reverse psychology—please don't buy it.", "author": "Unknown"},
    {"quote": "The elevator to success is out of order. You'll have to use the stairs… one step at a time.", "author": "Joe Girard"},
    {"quote": "I dream of a better tomorrow, where chickens can cross the road and not be questioned about their motives.", "author": "Unknown"},
    {"quote": "Don’t worry if plan A doesn’t work out. There are 25 more letters in the alphabet.", "author": "Unknown"},
    {"quote": "A bank is a place that will lend you money if you can prove that you don’t need it.", "author": "Bob Hope"},
    {"quote": "We are all here on earth to help others; what on earth the others are here for I don't know.", "author": "W. H. Auden"},
    {"quote": "If you think education is expensive, try ignorance.", "author": "Derek Bok"},
    {"quote": "I never forget a face, but in your case, I’ll be glad to make an exception.", "author": "Groucho Marx"},
    {"quote": "Some cause happiness wherever they go; others whenever they go.", "author": "Oscar Wilde"},
    {"quote": "The best way to lie is to tell the truth… carefully edited truth.", "author": "Unknown"},
    {"quote": "My opinions may have changed, but not the fact that I am right.", "author": "Ashleigh Brilliant"},
    {"quote": "The trouble with having an open mind is that people will insist on coming along and trying to put things in it.", "author": "Terry Pratchett"},
    {"quote": "I find television very educating. Every time somebody turns it on, I go into the other room and read a book.", "author": "Groucho Marx"},
    {"quote": "I know that there are people who do not love their fellow man, and I hate people like that!", "author": "Tom Lehrer"},
    {"quote": "Never follow anyone else’s path. Unless you’re in the woods and you’re lost and you see a path. Then by all means, follow that path.", "author": "Ellen DeGeneres"},
    {"quote": "Why yes, I do frequently burst out in song. Why do you ask?", "author": "Unknown"},
    {"quote": "Adults are always asking little kids what they want to be when they grow up because they’re looking for ideas.", "author": "Paula Poundstone"},
    {"quote": "I’m not great at the advice. Can I interest you in a sarcastic comment?", "author": "Chandler Bing"},
    {"quote": "I like long walks, especially when they are taken by people who annoy me.", "author": "Fred Allen"},
    {"quote": "I have enough money to last me the rest of my life, unless I buy something.", "author": "Jackie Mason"},
    {"quote": "My favorite exercise is a cross between a lunge and a crunch. I call it lunch.", "author": "Unknown"},
    {"quote": "I followed a diet but it didn’t follow me back.", "author": "Unknown"},
    {"quote": "I asked the gym instructor if he could teach me to do the splits. He replied, 'How flexible are you?' I said, 'I can’t make it on Tuesdays.'", "author": "Unknown"},
    {"quote": "If life gives you melons, you might be dyslexic.", "author": "Unknown"},
    {"quote": "My bed and I love each other, but my alarm clock keeps trying to break us up.", "author": "Unknown"},
    {"quote": "Some people get lost in thought because it’s unfamiliar territory.", "author": "Paul Fix"},
    {"quote": "The only mystery in life is why the kamikaze pilots wore helmets.", "author": "Al McGuire"},
    {"quote": "I bought a dog from a blacksmith. As soon as I got it home, it made a bolt for the door.", "author": "Unknown"},
    {"quote": "I’m reading a book about anti-gravity. It’s impossible to put down.", "author": "Unknown"},
    {"quote": "I accidentally handed my wife a glue stick instead of chapstick. She still isn’t talking to me.", "author": "Unknown"},
    {"quote": "Never trust math teachers who use graph paper — they’re always plotting something.", "author": "Unknown"},
    {"quote": "Before you criticize someone, walk a mile in their shoes. That way, when you do criticize them, you’re a mile away and you have their shoes.", "author": "Jack Handey"},
    {"quote": "To be sure of hitting the target, shoot first and call whatever you hit the target.", "author": "Ashleigh Brilliant"},
    {"quote": "I don’t suffer from insanity—I enjoy every minute of it.", "author": "Unknown"},
    {"quote": "I started out with nothing, and I still have most of it.", "author": "Unknown"},
    {"quote": "Don’t take life too seriously. You’ll never get out of it alive.", "author": "Elbert Hubbard"},
     {"quote": "I’m on a seafood diet. I see food and I eat it.", "author": "Unknown"},
    {"quote": "I didn’t fail the test. I just found 100 ways to do it wrong.", "author": "Benjamin Franklin"},
    {"quote": "I was going to take over the world, but I got distracted by something shiny.", "author": "Unknown"},
    {"quote": "I tried to catch some fog earlier. I mist.", "author": "Unknown"},
    {"quote": "The only time to be positive you’re in the right path is when you’re on the edge.", "author": "Unknown"},
    {"quote": "A day without sunshine is like, you know, night.", "author": "Steve Martin"},
    {"quote": "If at first you don’t succeed, then skydiving is not for you.", "author": "Unknown"},
    {"quote": "Why don’t skeletons fight each other? They don’t have the guts.", "author": "Unknown"},
    {"quote": "I’d agree with you, but then we’d both be wrong.", "author": "Unknown"},
    {"quote": "I'm writing a book. I've got the page numbers done.", "author": "Steven Wright"},
    {"quote": "I have a lot of growing up to do. I realized that the other day inside my fort.", "author": "Unknown"},
    {"quote": "I'm reading a book on the history of glue. I just can’t seem to put it down.", "author": "Unknown"},
    {"quote": "Some graduate with honors, some without them, but all get the same diploma.", "author": "Unknown"},
    {"quote": "I know they say that money talks, but all mine says is ‘Goodbye.’", "author": "Unknown"},
    {"quote": "I told my wife she was drawing her eyebrows too high. She looked surprised.", "author": "Unknown"},
    {"quote": "I went to buy some camo pants, but couldn’t find any.", "author": "Unknown"},
    {"quote": "Why don't programmers like nature? It has too many bugs.", "author": "Unknown"},
    {"quote": "I’m not lazy, I’m just in energy-saving mode.", "author": "Unknown"},
    {"quote": "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you.'", "author": "Unknown"},
    {"quote": "I’m writing a book about reverse psychology. Don’t buy it.", "author": "Unknown"},
    {"quote": "Why don’t oysters donate to charity? Because they are shellfish.", "author": "Unknown"},
    {"quote": "My wife told me I should do lunges to stay in shape. That would be a big step forward.", "author": "Unknown"},
    {"quote": "I don't suffer from insanity. I enjoy every minute of it.", "author": "Unknown"},
    {"quote": "I’ve just written a song about tortillas; actually, it’s more of a rap.", "author": "Unknown"},
    {"quote": "I didn't want to believe that my dad was stealing from his job as a traffic cop, but when I got home all the signs were there.", "author": "Unknown"},
    {"quote": "I'd tell you a chemistry joke but I know I wouldn't get a reaction.", "author": "Unknown"},
    {"quote": "I had a dream that I was a muffler last night. I woke up exhausted!", "author": "Unknown"},
    {"quote": "I used to play piano by ear, but now I use my hands.", "author": "Unknown"},
    {"quote": "I love deadlines. I love the whooshing noise they make as they go by.", "author": "Douglas Adams"},
    {"quote": "I’m writing a book. I’ve got the first sentence done. The second one will be coming soon.", "author": "Unknown"},
    {"quote": "I was addicted to the hokey pokey, but I turned myself around.", "author": "Unknown"},
    {"quote": "Why don’t skeletons ever use cell phones? They don’t have the guts.", "author": "Unknown"},
    {"quote": "I have a fear of speed bumps, but I am slowly getting over it.", "author": "Unknown"},
    {"quote": "I can’t believe I got fired from the calendar factory. All I did was take a day off.", "author": "Unknown"}

    ],
    "random": [
        {"quote": "Be yourself; everyone else is already taken.", "author": "Oscar Wilde"},
        {"quote": "In the middle of difficulty lies opportunity.", "author": "Albert Einstein"},
        {"quote": "Success is not final, failure is not fatal: it is the courage to continue that counts.", "author": "Winston Churchill"},
        {"quote": "Do not go where the path may lead, go instead where there is no path and leave a trail.", "author": "Ralph Waldo Emerson"},
        {"quote": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius"},
        {"quote": "Not all those who wander are lost.", "author": "J.R.R. Tolkien"},
        {"quote": "You miss 100% of the shots you don't take.", "author": "Wayne Gretzky"},
        {"quote": "What lies behind us and what lies before us are tiny matters compared to what lies within us.", "author": "Ralph Waldo Emerson"},
        {"quote": "Act as if what you do makes a difference. It does.", "author": "William James"},
        {"quote": "Whether you think you can or you think you can’t, you’re right.", "author": "Henry Ford"},
        {"quote": "Everything you can imagine is real.", "author": "Pablo Picasso"},
        {"quote": "Strive not to be a success, but rather to be of value.", "author": "Albert Einstein"},
        {"quote": "Dream big and dare to fail.", "author": "Norman Vaughan"},
        {"quote": "The best way out is always through.", "author": "Robert Frost"},
        {"quote": "Change your thoughts and you change your world.", "author": "Norman Vincent Peale"},
    {"quote": "Everything has beauty, but not everyone can see it.", "author": "Confucius"},
    {"quote": "You have as many hours in the day as Beyoncé.", "author": "Unknown"},
    {"quote": "Life is what happens when you're busy making other plans.", "author": "John Lennon"},
    {"quote": "Happiness is not something ready-made. It comes from your own actions.", "author": "Dalai Lama"},
    {"quote": "Your time is limited, so don’t waste it living someone else’s life.", "author": "Steve Jobs"},
    {"quote": "You don't have to be great to start, but you have to start to be great.", "author": "Zig Ziglar"},
    {"quote": "Live as if you were to die tomorrow. Learn as if you were to live forever.", "author": "Mahatma Gandhi"},
    {"quote": "Don’t wait. The time will never be just right.", "author": "Napoleon Hill"},
    {"quote": "I would rather die on my feet than live on my knees.", "author": "Emiliano Zapata"},
    {"quote": "Success usually comes to those who are too busy to be looking for it.", "author": "Henry David Thoreau"},
    {"quote": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Zig Ziglar"},
    {"quote": "The best revenge is massive success.", "author": "Frank Sinatra"},
    {"quote": "The only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"quote": "Success is not how high you have climbed, but how you make a positive difference to the world.", "author": "Roy T. Bennett"},
    {"quote": "The harder you work for something, the greater you'll feel when you achieve it.", "author": "Anonymous"},
    {"quote": "We may encounter many defeats, but we must not be defeated.", "author": "Maya Angelou"},
    {"quote": "You can't go back and change the beginning, but you can start where you are and change the ending.", "author": "C.S. Lewis"},
    {"quote": "Don't limit your challenges. Challenge your limits.", "author": "Anonymous"},
    {"quote": "Opportunities don't happen. You create them.", "author": "Chris Grosser"},
    {"quote": "I never dreamed about success. I worked for it.", "author": "Estée Lauder"},
    {"quote": "Do what you can with all you have, wherever you are.", "author": "Theodore Roosevelt"},
    {"quote": "I’ve missed more than 9,000 shots in my career. I’ve lost almost 300 games. 26 times I’ve been trusted to take the game-winning shot and missed. I’ve failed over and over and over again in my life. And that is why I succeed.", "author": "Michael Jordan"},
    {"quote": "You only live once, but if you do it right, once is enough.", "author": "Mae West"},
    {"quote": "Your time is limited, so don't waste it living someone else's life.", "author": "Steve Jobs"},
    {"quote": "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.", "author": "Roy T. Bennett"},
    {"quote": "There are no limits to what you can accomplish, except the limits you place on your own thinking.", "author": "Brian Tracy"},
    {"quote": "It always seems impossible until it’s done.", "author": "Nelson Mandela"},
    {"quote": "Hardships often prepare ordinary people for an extraordinary destiny.", "author": "C.S. Lewis"},
    {"quote": "Don’t watch the clock; do what it does. Keep going.", "author": "Sam Levenson"},
    {"quote": "Everything you've ever wanted is on the other side of fear.", "author": "George Addair"},
    {"quote": "You must be the change you wish to see in the world.", "author": "Mahatma Gandhi"},
    {"quote": "If you can dream it, you can do it.", "author": "Walt Disney"},
    {"quote": "The journey of a thousand miles begins with one step.", "author": "Lao Tzu"},
    {"quote": "Believe you can and you're halfway there.", "author": "Theodore Roosevelt"},
    {"quote": "In three words I can sum up everything I've learned about life: it goes on.", "author": "Robert Frost"},
    {"quote": "The only thing standing between you and your goal is the story you keep telling yourself as to why you can't achieve it.", "author": "Jordan Belfort"},
    {"quote": "What we think, we become.", "author": "Buddha"},
    ],
    "business": [
    {"quote": "Success is not in what you have, but who you are.", "author": "Bo Bennett"},
    {"quote": "Don't watch the clock; do what it does. Keep going.", "author": "Sam Levenson"},
    {"quote": "Opportunities don't happen, you create them.", "author": "Chris Grosser"},
    {"quote": "Do not wait to strike till the iron is hot, but make it hot by striking.", "author": "William Butler Yeats"},
    {"quote": "The secret of getting ahead is getting started.", "author": "Mark Twain"},
    {"quote": "Your most unhappy customers are your greatest source of learning.", "author": "Bill Gates"},
    {"quote": "I find that the harder I work, the more luck I seem to have.", "author": "Thomas Jefferson"},
    {"quote": "Success is not final, failure is not fatal: It is the courage to continue that counts.", "author": "Winston Churchill"},
    {"quote": "An investment in knowledge pays the best interest.", "author": "Benjamin Franklin"},
    {"quote": "I’m for truth no matter who tells it. I’m for justice no matter who it’s for or against.", "author": "Malcolm X"},
    {"quote": "Success is the sum of small efforts, repeated day in and day out.", "author": "Robert Collier"},
    {"quote": "The best way to start is to stop talking and start doing.", "author": "Walt Disney"},
    {"quote": "Don't be afraid to give up the good to go for the great.", "author": "John D. Rockefeller"},
    {"quote": "Risk more than others think is safe. Dream more than others think is practical.", "author": "Howard Schultz"},
    {"quote": "The only place where success comes before work is in the dictionary.", "author": "Vidal Sassoon"},
    {"quote": "Success is walking from failure to failure with no loss of enthusiasm.", "author": "Winston Churchill"},
    {"quote": "The harder you work for something, the greater you'll feel when you achieve it.", "author": "Unknown"},
    {"quote": "If you don't build your dream, someone else will hire you to help them build theirs.", "author": "Dhirubhai Ambani"},
    {"quote": "Your brand is what people say about you when you're not in the room.", "author": "Jeff Bezos"},
    {"quote": "The way to get started is to quit talking and begin doing.", "author": "Walt Disney"},
    {"quote": "Innovation distinguishes between a leader and a follower.", "author": "Steve Jobs"},
    {"quote": "The function of leadership is to produce more leaders, not more followers.", "author": "Ralph Nader"},
    {"quote": "Business opportunities are like buses, there's always another one coming.", "author": "Richard Branson"},
    {"quote": "The purpose of business is to create and keep a customer.", "author": "Peter Drucker"},
    {"quote": "Don't let the noise of others' opinions drown out your own inner voice.", "author": "Steve Jobs"},
    {"quote": "Time is money. Wasted time means wasted money means trouble.", "author": "Shirley Temple"},
    {"quote": "What you do today can improve all your tomorrows.", "author": "Ralph Marston"},
    {"quote": "Small daily improvements over time lead to stunning results.", "author": "Robin Sharma"},
    {"quote": "Great things in business are never done by one person. They're done by a team of people.", "author": "Steve Jobs"},
    {"quote": "The only limit to our realization of tomorrow is our doubts of today.", "author": "Franklin D. Roosevelt"},
    {"quote": "It’s not about ideas. It’s about making ideas happen.", "author": "Scott Belsky"},
    {"quote": "A business that makes nothing but money is a poor business.", "author": "Henry Ford"},
    {"quote": "Fail often so you can succeed sooner.", "author": "Tom Kelley"},
    {"quote": "Nothing will work unless you do.", "author": "Maya Angelou"},
    {"quote": "If you're not a risk taker, you should get the hell out of business.", "author": "Ray Kroc"},
    {"quote": "Success is how high you bounce when you hit bottom.", "author": "George S. Patton"},
    {"quote": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar"},
    {"quote": "A goal without a plan is just a wish.", "author": "Antoine de Saint-Exupéry"},
    {"quote": "Don’t be afraid to give up the good to go for the great.", "author": "John D. Rockefeller"},
    {"quote": "You miss 100% of the shots you don’t take.", "author": "Wayne Gretzky"},
    {"quote": "If you are not willing to risk the usual, you will have to settle for the ordinary.", "author": "Jim Rohn"},
    {"quote": "To be successful, you must act big, think big and talk big.", "author": "Aristotle Onassis"},
    {"quote": "Success is not the key to happiness. Happiness is the key to success.", "author": "Albert Schweitzer"},
    {"quote": "The best way to predict the future is to create it.", "author": "Abraham Lincoln"},
    {"quote": "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. And the only way to do great work is to love what you do.", "author": "Steve Jobs"},
    {"quote": "Success seems to be connected with action. Successful people keep moving. They make mistakes, but they don't quit.", "author": "Conrad Hilton"},
    {"quote": "Don’t wait for the perfect moment. Take the moment and make it perfect.", "author": "Zoey Sayward"},
    {"quote": "Every strike brings me closer to the next home run.", "author": "Babe Ruth"},
    {"quote": "I am not a product of my circumstances. I am a product of my decisions.", "author": "Stephen Covey"},
    {"quote": "The future belongs to those who believe in the beauty of their dreams.", "author": "Eleanor Roosevelt"},
    {"quote": "Do one thing every day that scares you.", "author": "Eleanor Roosevelt"},
    {"quote": "An entrepreneur is someone who jumps off a cliff and builds a plane on the way down.", "author": "Reid Hoffman"},
    {"quote": "The best way to find yourself is to lose yourself in the service of others.", "author": "Mahatma Gandhi"},
    {"quote": "Don't wait for opportunity. Create it.", "author": "Unknown"},
    {"quote": "A successful man is one who can lay a firm foundation with the bricks others have thrown at him.", "author": "David Brinkley"}
]

}

# Duplicate finder func:
all_quotes = []
for category, category_quotes in quotes.items():
    for q in category_quotes:
        if (q['quote'], q['author']) in all_quotes:
            print(f"Duplicate found: {q['quote']} by {q['author']}")  # Print duplicates
        else:
            all_quotes.append((q['quote'], q['author']))

# Route for getting a random quote, not in use

@app.route('/quote/<category>')
def get_route(category):
    if category == "all":
        all_quotes = [q for quotes_list in quotes.values() for q in quotes_list]
        return jsonify({"quote": random.choice(all_quotes)})
    else:
        category_quotes = quotes.get(category, quotes["random"])
        return jsonify({"quote": random.choice(category_quotes)})

# Route for getting all quotes

@app.route('/quotes')
def get_all_quotes():
    all_quotes = []
    for category, items in quotes.items():
        for q in items:
            all_quotes.append({**q, "category": category})
    return jsonify(all_quotes)

if __name__ == '__main__':
    app.run(debug=True)

# Route for subscribing to a quote via form

@app.route('/subscribe', methods=['POST'])
def subscribe():
    email = request.form['email']
    if email not in subscribers:
        subscribers.append(email)
        return jsonify({"message": "You have been subscribed!"})
    else:
        return jsonify({"message": "You are already subscribed!"})
    

# Route for unsubscribing from a quote via form

@app.route('/unsubscribe', methods=['POST'])
def unsubscribe():
    email = request.form['email']
    if email in subscribers:
        subscribers.remove(email)
        return jsonify({"message": "Unsubsribed successfully!"})
    else:
        return jsonify({"message": "You were not subscribed."})